settings:
  title: 'EDED Status Page'
  url: 'https://status.eded.cc' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
#   - id: workers-cloudflare-com # unique identifier
#     name: workers.cloudflare.com
#     description: 'You write code. They handle the rest.' # default=empty
#     url: 'https://workers.cloudflare.com/' # URL to fetch
#     method: GET # default=GET
#     expectStatus: 200 # operational status, default=200
#     followRedirect: false # should fetch follow redirects, default=false


  - id: eded-cc
    name: eded.cc
    #description: ''
    url: 'https://eded.cc/'
    method: GET
    expectStatus: 200
    
  - id: go-eded-cc
    name: g.eded.cc
    #dscription: 'Built for anything connected to the Internet.'
    url: 'https://go.eded.cc/'
    method: GET
    expectStatus: 200
